-- AlterTable
ALTER TABLE "public"."Content" ADD COLUMN     "commentCount" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "length" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "likes" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "shares" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "watchTime" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "public"."User" ADD COLUMN     "reputation" DOUBLE PRECISION NOT NULL DEFAULT 0;
